### ISSUE TITLE
bcrypt w/ windows error 

### ISSUE THREAD

**Issue by DonRichards** [connor11528/node-jwt-intro#3]
Trying to install bcrypt in a windows 10 environment for development.

http://cleechtech.github.io/2015/10/23/use-express-angular-and-jwt-to-make-a-secure-app/
& 
http://vujade.co/nodejs-environment-setup-with-bcrypt-module/
I was able to manually add bcrypt inside of python's pip but that didn't make any change

npm-debug.log

> https://gist.github.com/DonRichards/8f6f4e183e401501b879

**Comment by connor11528** [comment]
what node.js and python versions are you running? I was running in to trouble installing modules with newer versions. Check this node.js issue here: https://github.com/nodejs/node-gyp/issues/154

Can you clone this repo and run an npm install? What error do you get?

**Comment by DonRichards** [comment]
Node (x64) v4.1.2
Python 2.7.10
NPM 2.14.4
node-gyp v3.0.3

I did clone the repo and the errors are in this https://gist.github.com/DonRichards/8f6f4e183e401501b879

```
gyp ERR! Build Error
gyp ERR! stack Error: 'C;\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe' failed with exit code: 1
....
```

**Comment by connor11528** [comment]
Ok methinks it's an error with node-gyp and node versioning. We are using bcrypt version "^0.8.4"

For me it's working with this version of node:

```
$ node --version
v0.12.7
```

The [bcrypt site](https://github.com/ncb000gt/node.bcrypt.js) has a version compatibility table. Try upgrading node or even using a lesser version of bcrypt. Also that module is only for password hashing, so if you want to use this as a starter and use a different tool for password hashing that is totally fine. The bcrypt module is only used in `server/utils.js`

There is also all the [node-gyp requirements](https://github.com/nodejs/node-gyp) to make things run smooth

**Comment by DonRichards** [comment]
Updated Node & Node-gyp and current error is gone Node-gyp v3.1.0 & Node v5.1.0

**Comment by connor11528** [comment]
Awesome, thanks for update!
